# Generated by Django 5.2.7 on 2025-12-15 17:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_area', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_padre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'area',
                'ordering': ['cod_area', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(db_column='CI', max_length=11)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=150)),
                ('es_baja', models.BooleanField(db_column='Baja')),
                ('area', models.ForeignKey(db_column='Area', on_delete=django.db.models.deletion.CASCADE, to='asistencia.area')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'trabajador',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ResponsableArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='asistencia.area')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsable de Área',
                'verbose_name_plural': 'Responsables de Áreas',
                'db_table': 'responsable_area',
                'ordering': ['area__cod_area', 'usuario__username'],
                'unique_together': {('usuario', 'area')},
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('Asistió puntual', 'Asistió puntual'), ('Asistió con retardo', 'Asistió con retardo'), ('Falta justificada', 'Falta justificada'), ('Falta injustificada', 'Falta injustificada'), ('Vacaciones', 'Vacaciones'), ('Incapacidad médica', 'Incapacidad'), ('Permiso con goce de sueldo', 'Permiso con goce de sueldo'), ('Permiso sin goce de sueldo', 'Permiso sin goce de sueldo'), ('Teletrabajo', 'Teletrabajo'), ('Licencia especial', 'Licencia especial')], db_column='Estado', default='Asistió puntual', max_length=150, null=True)),
                ('fecha_asistencia', models.DateField(db_column='Fecha_Asistencia', default=datetime.date.today)),
                ('area', models.ForeignKey(db_column='Area', on_delete=django.db.models.deletion.CASCADE, to='asistencia.area')),
                ('trabajador', models.ForeignKey(db_column='Trabajador', on_delete=django.db.models.deletion.CASCADE, to='asistencia.trabajador')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencia',
                'ordering': ['trabajador'],
                'unique_together': {('trabajador', 'fecha_asistencia')},
            },
        ),
    ]
