# Generated by Django 5.2.7 on 2025-12-18 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_column='Clave', max_length=100)),
                ('clave_id', models.CharField(db_column='Clave_id', max_length=10)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
                'ordering': ['clave'],
            },
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='trabajador',
            field=models.ForeignKey(db_column='Trabajador', default=None, on_delete=django.db.models.deletion.CASCADE, to='asistencia.trabajador'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.OneToOneField(db_column='Estado', default=None, on_delete=django.db.models.deletion.CASCADE, to='asistencia.estado'),
        ),
    ]
