# Generated by Django 5.2.7 on 2025-12-18 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_incidencia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.ForeignKey(db_column='Estado', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencia.estado'),
        ),
    ]
