# Generated by Django 5.2.7 on 2026-01-05 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_incidencia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsablearea',
            name='area',
            field=models.ForeignKey(db_column='Area', on_delete=django.db.models.deletion.CASCADE, to='asistencia.area'),
        ),
    ]
